### PR TITLE
Google Analytics

### PR DESCRIPTION
**Pull request by Pipe-to-Grep**

### CODE REVIEW

**Comment by CameronSamuels** [comment]
Please create this pull request's commits from the master branch, not from the `MD-edits` branch. So basically add the Google Analytics commits from the master branch, not from the branch that already had the contributing commits.

I will close this pr. So don't edit the file that has the commented line. Just "add" the whole line from the master branch, not removing the `//` from the contributing branch.

**Comment by Pipe-to-Grep** [comment]
You have me wildly confused

**Comment by CameronSamuels** [comment]
Just go to https://github.com/xeleration/memerator/edit/master/js/script.js do you edit the master branch, not the MD-edit branch.

**Comment by Pipe-to-Grep** [comment]
You're speaking cameron language. I need you to speak english

**Comment by CameronSamuels** [comment]
I am speaking in git language not cameron language

**Pull request closed without merging**
